name: Docs

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  docs:
    name: Build and deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev pkg-config libgtk-4-dev
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo doc --no-deps
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
